version: '3.0'
services:
  rtmp_server:
    image: tiangolo/nginx-rtmp:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./stream:/tmp/hls/live
    ports:
      - "1935:1935"
      - "8080:8080"

  node_server:
    build: .
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./node_modules:/app/node_modules
      - ./stream:/tmp/hls/live
    ports:
      - "3000:3000"
    command: npm run start